### ISSUE TITLE
no possible to use named Parameterized JUnit tests in test classes inherited from AbstractPluginIT

### ISSUE THREAD

**Issue by 62mkv** [buschmais/jqa-plugin-common#3]
Hi. 

I am not sure is this a jQAssistant issue or a JUnit one. So, here's the gist: 

If you use a 
```
@RunWith(Parameterized.class)
public class InvalidFileFormatTest extends BaseTest {
    @Parameterized.Parameters(name = "{index}: {0}")
    public static Collection<Object[]> data() {
 ..}
}
```
(i.e., with `name` annotation parameter defined on a parameters' collection)
and 
`public class BaseTest extends AbstractPluginIT {...}` 

then all tests in the suite fail with 

```
java.lang.NullPointerException
	at com.buschmais.jqassistant.plugin.common.test.AbstractPluginIT.startStore(AbstractPluginIT.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
...
```

seems like it's messing with 
```
    private class TestContextRule extends TestWatcher {
``` 

somehow. 

This does not happen, if `name` parameter is omitted on the `@Parameterized.Parameters` annotation.

Has it been observed by anyone else ? What are the suggestions for mitigation? Thanks!

JUnit version 4.12, jQAssistant version 1.6.0

**Comment by 62mkv** [comment]
it seems as though 

```
        protected void starting(Description description) {
            Class testClass = description.getTestClass();

            try {
                String methodName = description.getMethodName();
                if (methodName.matches(".*\\[\\d+\\]$")) {
                    methodName = methodName.replaceAll("\\[\\d+\\]", "");
                }

                this.testMethod = testClass.getDeclaredMethod(methodName);
            } catch (NoSuchMethodException var4) {
                Assert.fail(var4.getMessage());
            }

        }
```

might be the culprit. Description, that it receives in case of `name={0}` annotation parameter value being used, looks as follows: 

`checkFileWithInvalidFormat[command/get_usr_supplier_address_spoiled_structure.mcmd](kn.swift.tools.jqassistant.moca.scanner.InvalidFileFormatTest)`

so `methodName` is calculated as `checkFileWithInvalidFormat[command/get_usr_supplier_address_spoiled_structure.mcmd]`, which leads to `NoSuchMethodException` exception in the 

` this.testMethod = testClass.getDeclaredMethod(methodName);` statement

**Comment by 62mkv** [comment]
so probably these lines 
```
                if (methodName.matches(".*\\[\\d+\\]$")) {
                    methodName = methodName.replaceAll("\\[\\d+\\]", "");
                }
``` might be replaced with something wider than `\d` inside the `[]` brackets

**Comment by 62mkv** [comment]
ok, so I wanted to create a pull-request but there's no branch for 1.6.x and 1.7.0 is completely different, it does not even have the code in question. (it seems to be migrated to JUnit 5). so, this might be closed I suppose
